apiVersion: v1
kind: Pod
metadata: 
  name: annotations
  labels:
    project: roboshop
    duration: 15h
  annotations:
    description: "this is the demo of the anotations"
    jenkins: "https://jenkins/job/catalogue-data/3"
spec:
  containers:
    name: nginx
    image: nginx