apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  lables:
    purpose: practice
    project: dummy
    env: dev
spec:
  replicas: 2
  lablelsFrom:
    purpose: practice
    project: dummy
    env: dev
  template:
    metadata:
      name: nginx
      lables:
        purpose: practice
        project: dummy
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
