apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    purpose: practice
    project: dummy
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      purpose: practice
      project: dummy
      env: dev
  template:
    metadata:
      name: nginx
      labels:
        purpose: practice
        project: dummy
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
