#headless-service
apiVersion: v1
kind: Service
metadata: 
  name: headless-service
  labels:
    project: roboshop
    purpose: practice
spec:
  clusterIP: none
  selectors:
    project: roboshop
    purpose: practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: statefulset-service
  labels:
    purpose: practice
    project: roboshop
spec:
  type: LoadBalancer
  selectors:
    purpose: practice
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:
    matchLabels:
      purpose: practice
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: practice
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: #pvc in statefulset
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class" #Storage class name should be given for PVC
      resources:
        requests:
          storage: 1Gi