apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
   purpose: demo
spec:
  containers:
  - name: nginx
    image: nginz
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]

