apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    purpose: secretpod
    environment: devops
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: Secret

    