apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    environment: dev
    project: roboshop
    purpose: pod-service
  ports:
  - protocol: tcp
    port: 80 #service port
    targetport: 80 #container port




---

apiVersion: v1
kind: Pod
metadata:
  name: pod-service
  labels:
    environment: dev
    project: roboshop
    purpose: pod-service
  spec:
    containers:
    - name: nginx
      image: nginx  
