apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    purpose: service-np
spec:
  type: nodeport
  selector:
    project: roboshop
    environment: dev
    purpose: service-np
  ports:
    - protocol: TCP  
      port: 80
      targetPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  labels:
      project: roboshop
      environment: dev
      purpose: service-np
spec:
  containers:
  - name: nginx
    image: nginx