apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-Replicaset
  lable: 
    project: roboshop
    environment: dev
spec:
  replicas: 2 
  selector:
    matchlables:
      purpose: rs-demo
      project: roboshop
      environment: dev 

  template:
    metadata:
      lables:
        purpose: rs-demo
        project: roboshop
        environment: dev
  spec:
    containers:
    - name: nginx
      image: nginx