apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels: 
    project: roboshop
    environment: dev
    app: nginx
spec:
  replicas: 2 
  selector:
    matchLables:
      purpose: rs-demo
      project: roboshop
      environment: dev 

  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
