apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels:
    project: roboshop
    environment: dev
    purpose: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      purpose: deployment
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        purpose: deployment
    spec:
      containers:
       - name: nginx
         image: nginx:latest
