apiVersion: app/v1
kind: Deployment
metadata: 
  name: deployment
  labels:
    project: roboshop
    environment: dev
    purpose: deployment
spec:
  replica: 2
  selector:
    matchlabels:
      project: roboshop
      environment: dev
      purpose: deployment
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        purpose: deployment
  spec:
    containers:
    - name: nginx
      image: nginx
