apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-ebs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: dynamic-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-ebs
spec:
  containers:
  - name: dynamic-ebs
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: dynamic-ebs