apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-ebs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: {EBS volume ID}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-ebs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: static-ebs
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: 
    - name: persistance-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistance-storage
    PersistentVolumeClaim:
    claimName: ebs-static

---

apiVersion: v1
kind: Service
metadata:
  name: static-ebs
  metadata:
    labels:
      project: roboshop
      purpose: ebs-static-demo
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    protocal: TCP
    port: 80
    targetPort: 8080


